project_id = "xwomfroxqqwfpugvxryv"

[functions.validate-dev-key]
verify_jwt = false

[functions.dev-crud]
verify_jwt = false

[functions.upload-image]
verify_jwt = false

[functions.analyze-project]
verify_jwt = false
